Repository woowa-techcamp-2021/deal-7, pull requests merged in 2021-07, with the labels that each got.

#23 [Feature/#6] 공통으로 사용할 요소 추가
  client/public/font/BMHANNAAir.otf
  client/public/font/BMHANNAPro.otf
  client/public/images/icons/add.svg
  client/public/images/icons/category.svg
  client/public/images/icons/check.svg
  client/public/images/icons/close.svg
  client/public/images/icons/down.svg
  client/public/images/icons/dropdown.svg
  client/public/images/icons/heart.svg
  client/public/images/icons/left.svg
  client/public/images/icons/location.svg
  client/public/images/icons/logout.svg
  client/public/images/icons/menu.svg
  client/public/images/icons/message.svg
  client/public/images/icons/photo.svg
  client/public/images/icons/right.svg
  client/public/images/icons/send.svg
  client/public/images/icons/user.svg
  client/src/index.css
  client/src/reset.css
  prettier.config.js
Labels: FE

#27 [Feature/#3] 메인 페이지-카테고리 슬라이드 레이아웃 개발
  client/src/dummy-file.js
  client/src/views/page-components/MainPage/Category/Category.css
  client/src/views/page-components/MainPage/Category/Category.js
  client/src/views/page-components/MainPage/CategorySlide/CategorySlide.css
  client/src/views/page-components/MainPage/CategorySlide/CategorySlide.js
  client/src/views/page-components/MainPage/MainPage.css
  client/src/views/page-components/MainPage/MainPage.js
  client/src/views/page-components/MainPage/ProductsWrap/ProductsWrap.js
Labels: FE, 작업 완료

#28 [Feature/#1] 메인 페이지-내 계정 슬라이드 레이아웃
  .github/pull_request_template.md
  client/public/images/createdBaeminStyleImage/lets-with-me-2.png
  client/public/images/createdBaeminStyleImage/lets-with-me.png
  client/public/images/createdBaeminStyleImage/login-btn.png
  client/public/images/createdBaeminStyleImage/login-logo.png
  client/public/images/createdBaeminStyleImage/logout-btn.png
  client/public/images/createdBaeminStyleImage/signup-btn.png
  client/public/images/createdBaeminStyleImage/underline-baemin-color.png
  client/public/images/createdBaeminStyleImage/underline-black-color.png
  client/public/images/createdBaeminStyleImage/we-are-the-world.png
  client/src/constants/imagePath.js
  client/src/views/components/BaeminInput/BaeminInput.css
  client/src/views/components/BaeminInput/BaeminInput.js
  client/src/views/components/BaeminInputField/BaeminInputField.css
  client/src/views/components/BaeminInputField/BaeminInputField.js
  client/src/views/components/components.css
  client/src/views/page-components/MainPage/CategorySlide/CategorySlide.css
  client/src/views/page-components/MainPage/LoginFieldset/LoginFieldset.css
  client/src/views/page-components/MainPage/LoginFieldset/LoginFieldset.js
  client/src/views/page-components/MainPage/LoginScreen/LoginScreen.css
  client/src/views/page-components/MainPage/LoginScreen/LoginScreen.js
  client/src/views/page-components/MainPage/LogoutScreen/LogoutScreen.css
  client/src/views/page-components/MainPage/LogoutScreen/LogoutScreen.js
  client/src/views/page-components/MainPage/MainPage.css
  client/src/views/page-components/MainPage/SignupFieldset/SignupFieldset.css
  client/src/views/page-components/MainPage/SignupFieldset/SignupFieldset.js
  client/src/views/page-components/MainPage/SignupScreen/SignupScreen.css
  client/src/views/page-components/MainPage/SignupScreen/SignupScreen.js
  client/src/views/page-components/MainPage/UserSlide/UserSlide.css
  client/src/views/page-components/MainPage/UserSlide/UserSlide.js
Labels: FE, 작업 완료

#32 [Feature/#8] 채팅 목록 페이지 레이아웃 개발 및 스타일링
  client/src/index.css
  client/src/pages/chatListPage.html
  client/src/views/page-components/ChatListPage/ChatListPage.css
  client/src/views/page-components/ChatListPage/ChatListPage.js
  client/src/views/page-components/ChatListPage/ChatListPageHeader/ChatListPageHeader.css
  client/src/views/page-components/ChatListPage/ChatListPageHeader/ChatListPageHeader.js
  client/src/views/page-components/ChatListPage/ChatRoomList/ChatRoomList.css
  client/src/views/page-components/ChatListPage/ChatRoomList/ChatRoomList.js
Labels: FE, 작업 완료

#29 [Feature/#5] 상품 상세 페이지-캐로셀 구현하기 + 레이아웃 및 기능 구현 (삭제 확인 모달 추가)
  client/src/constants/productState.js
  client/src/index.css
  client/src/pages/productDetailPage.html
  client/src/utils/formatPrice.js
  client/src/views/components/CreateProductSlide/CategoryList/CategoryList.js
  client/src/views/components/CreateProductSlide/ContentInput/ContentInput.js
  client/src/views/components/CreateProductSlide/CreateProductFooter/CreateProductFooter.css
  client/src/views/components/CreateProductSlide/CreateProductFooter/CreateProductFooter.js
  client/src/views/components/CreateProductSlide/CreateProductSlide.css
  client/src/views/components/CreateProductSlide/CreateProductSlide.js
  client/src/views/components/CreateProductSlide/Header/CreateProductHeader.js
  client/src/views/components/CreateProductSlide/ImageContainer/ImageCardList/ImageCardList.css
  client/src/views/components/CreateProductSlide/ImageContainer/ImageCardList/ImageCardList.js
  client/src/views/components/CreateProductSlide/ImageContainer/ImageContainer.js
  client/src/views/components/CreateProductSlide/ImageContainer/ImageUploader/ImageUploader.js
  client/src/views/components/CreateProductSlide/PriceInput/PriceInput.js
  client/src/views/components/CreateProductSlide/TitleInput/TitleInput.js
  client/src/views/components/components.css
  client/src/views/page-components/ProductDetailPage/ProductDetail/Carousel/Carousel.css
  client/src/views/page-components/ProductDetailPage/ProductDetail/Carousel/Carousel.js
  client/src/views/page-components/ProductDetailPage/ProductDetail/Carousel/CarouselCount/CarouselCount.css
  client/src/views/page-components/ProductDetailPage/ProductDetail/Carousel/CarouselCount/CarouselCount.js
  client/src/views/page-components/ProductDetailPage/ProductDetail/DeleteConfirmModal/DeleteConfirmModal.css
  client/src/views/page-components/ProductDetailPage/ProductDetail/DeleteConfirmModal/DeleteConfirmModal.js
  client/src/views/page-components/ProductDetailPage/ProductDetail/ProductDetail.css
  client/src/views/page-components/ProductDetailPage/ProductDetail/ProductDetail.js
  client/src/views/page-components/ProductDetailPage/ProductDetail/ProductDetailBody/ProductDetailBody.css
  client/src/views/page-components/ProductDetailPage/ProductDetail/ProductDetailBody/ProductDetailBody.js
  client/src/views/page-components/ProductDetailPage/ProductDetail/ProductDetailFooter/ProductDetailFooter.css
  client/src/views/page-components/ProductDetailPage/ProductDetail/ProductDetailFooter/ProductDetailFooter.js
  client/src/views/page-components/ProductDetailPage/ProductDetail/ProductDetailHeader/ProductDetailHeader.css
  client/src/views/page-components/ProductDetailPage/ProductDetail/ProductDetailHeader/ProductDetailHeader.js
  client/src/views/page-components/ProductDetailPage/ProductDetail/ProductStateSelector/ProductStateSelector.css
  client/src/views/page-components/ProductDetailPage/ProductDetail/ProductStateSelector/ProductStateSelector.js
  client/src/views/page-components/ProductDetailPage/ProductDetail/SelectModal/SelectModal.css
  client/src/views/page-components/ProductDetailPage/ProductDetail/SelectModal/SelectModal.js
  client/src/views/page-components/ProductDetailPage/ProductDetail/SelectStateModal/SelectStateModal.css
  client/src/views/page-components/ProductDetailPage/ProductDetail/SelectStateModal/SelectStateModal.js
  client/src/views/page-components/ProductDetailPage/ProductDetailPage.css
  client/src/views/page-components/ProductDetailPage/ProductDetailPage.js
Labels: FE, 작업 완료

#30 [Feature/#4] 메인 페이지-메뉴 슬라이드 레이아웃 개발
  client/public/images/createdBaeminStyleImage/thung.png
  client/src/constants/emptyErrorMessage.js
  client/src/constants/imagePath.js
  client/src/dummy-file.js
  client/src/views/components/Product/Product.css
  client/src/views/components/Product/Product.js
  client/src/views/components/Thung/Thung.css
  client/src/views/components/Thung/Thung.js
  client/src/views/components/components.css
  client/src/views/page-components/MainPage/ChatListScreen/ChatListScreen.css
  client/src/views/page-components/MainPage/ChatListScreen/ChatListScreen.js
  client/src/views/page-components/MainPage/LikeListScreen/LikeListScreen.css
  client/src/views/page-components/MainPage/LikeListScreen/LikeListScreen.js
  client/src/views/page-components/MainPage/MainPage.css
  client/src/views/page-components/MainPage/MenuSlide/MenuSlide.css
  client/src/views/page-components/MainPage/MenuSlide/MenuSlide.js
  client/src/views/page-components/MainPage/ProductModifyModal/ProductModifyModal.css
  client/src/views/page-components/MainPage/ProductModifyModal/ProductModifyModal.js
  client/src/views/page-components/MainPage/SaleListScreen/SaleListScreen.css
  client/src/views/page-components/MainPage/SaleListScreen/SaleListScreen.js
  client/src/views/page-components/MainPage/UserSlide/UserSlide.css
Labels: FE, 작업 완료

#33 [Feature/#31] 메인 페이지-내 동네 설정하기 레이아웃 개발
  client/public/images/createdBaeminStyleImage/close.png
  client/public/images/createdBaeminStyleImage/district-notification.png
  client/public/images/createdBaeminStyleImage/ok.png
  client/src/constants/imagePath.js
  client/src/views/components/BaeminInput/BaeminInput.js
  client/src/views/components/BaeminInputField/BaeminInputField.css
  client/src/views/components/BaeminInputField/BaeminInputField.js
  client/src/views/components/components.css
  client/src/views/page-components/MainPage/MainPage.css
  client/src/views/page-components/MainPage/MainPage.js
  client/src/views/page-components/MainPage/MainPageNavBar/MainPageNavBar.js
  client/src/views/page-components/MainPage/TownCreateModal/TownCreateModal.css
  client/src/views/page-components/MainPage/TownCreateModal/TownCreateModal.js
  client/src/views/page-components/MainPage/TownModal/TownModal.js
  client/src/views/page-components/MainPage/TownPlusButton/TownPlusButton.css
  client/src/views/page-components/MainPage/TownPlusButton/TownPlusButton.js
  client/src/views/page-components/MainPage/TownSlide/TownSlide.css
  client/src/views/page-components/MainPage/TownSlide/TownSlide.js
  client/src/views/page-components/MainPage/TownSlideButton/TownSlideButton.css
  client/src/views/page-components/MainPage/TownSlideButton/TownSlideButton.js
Labels: FE, 작업 완료

#37 [Feature/#9] 채팅 상세 페이지, 기능 구현
  client/src/index.css
  client/src/pages/chatDetailPage.html
  client/src/views/components/CreateProductSlide/CategoryList/CategoryList.css
  client/src/views/components/CreateProductSlide/CategoryList/CategoryList.js
  client/src/views/components/CreateProductSlide/CreateProductSlide.js
  client/src/views/components/CreateProductSlide/ImageContainer/ImageCardList/ImageCardList.css
  client/src/views/components/CreateProductSlide/PriceInput/PriceInput.js
  client/src/views/page-components/ChatDetailPage/ChatDetaiPageHeader/ChatDetailPageHeader.css
  client/src/views/page-components/ChatDetailPage/ChatDetaiPageHeader/ChatDetailPageHeader.js
  client/src/views/page-components/ChatDetailPage/ChatDetailPage.css
  client/src/views/page-components/ChatDetailPage/ChatDetailPage.js
  client/src/views/page-components/ChatDetailPage/ChatDetailPageBody/ChatDetailPageBody.css
  client/src/views/page-components/ChatDetailPage/ChatDetailPageBody/ChatDetailPageBody.js
  client/src/views/page-components/ChatDetailPage/ChatDetailPageFooter/ChatDetailPageFooter.css
  client/src/views/page-components/ChatDetailPage/ChatDetailPageFooter/ChatDetailPageFooter.js
  client/src/views/page-components/ChatDetailPage/ChatDetailPageProduct/ChatDetailPageProduct.css
  client/src/views/page-components/ChatDetailPage/ChatDetailPageProduct/ChatDetailPageProduct.js
  client/src/views/page-components/ChatDetailPage/ChatRoomAlertModal/ChatRoomAlertModal.css
  client/src/views/page-components/ChatDetailPage/ChatRoomAlertModal/ChatRoomAlertModal.js
  client/src/views/page-components/ChatListPage/ChatListPageHeader/ChatListPageHeader.css
  client/src/views/page-components/ChatListPage/ChatRoomList/ChatRoomList.css
  client/src/views/page-components/ProductDetailPage/ProductDetail/ProductStateSelector/ProductStateSelector.js
Labels: FE, 작업 완료

#38 [feature/#36] 버튼 이름 부분을 클릭해도 town 상태가 변경되도록 수정
  client/src/views/page-components/MainPage/TownSlide/TownSlide.js
  client/src/views/page-components/MainPage/TownSlideButton/TownSlideButton.js
Labels: FE, 버그, 작업 완료

#35 [Feature/#34] 메인 페이지 글 쓰기 슬라이드 레이아웃 개발
  client/public/images/createdBaeminStyleImage/add-product-btn.png
  client/src/constants/imagePath.js
  client/src/utils/formatPrice.js
  client/src/views/components/CreateProductSlide/ImageContainer/ImageUploader/ImageUploader.css
  client/src/views/components/CreateProductSlide/PriceInput/PriceInput.css
  client/src/views/page-components/MainPage/CreateProductButton/CreateProductButton.css
  client/src/views/page-components/MainPage/CreateProductButton/CreateProductButton.js
  client/src/views/page-components/MainPage/CreateProductSlide/CreateProductSlide.css
  client/src/views/page-components/MainPage/CreateProductSlide/CreateProductSlide.js
  client/src/views/page-components/MainPage/MainPage.js
Labels: FE, 작업 완료

#40 Feature/#17
  .gitignore
  server/constants/errorMessages.js
  server/constants/regex.js
  server/constants/tokenExpiredPeriod.js
  server/controller/auth.js
  server/db.js
  server/middleware/checkToken.js
  server/query/authQuery.js
  server/query/createTableQuery.js
  server/router/auth.js
  server/router/authRouter.js
  server/router/product.js
  server/router/productRouter.js
  server/server.js
Labels: BE, 작업 완료

#41 [Feature/#21] ~/town API 개발
  server/constants/defaultTownValues.js
  server/constants/errorMessages.js
  server/controller/auth.js
  server/controller/town.js
  server/package-lock.json
  server/package.json
  server/query/townQuery.js
  server/router/auth.js
  server/router/town.js
  server/server.js
Labels: BE, 작업 완료

#44 [Feature/#11] 메인 페이지-내 계정 슬라이드 API 연결
  client/public/images/createdBaeminStyleImage/we-are-the-world.png
  client/src/apis/authAPI.js
  client/src/constants/regex.js
  client/src/constants/serverErrorMessages.js
  client/src/utils/checkUserLoginStatus.js
  client/src/utils/localStorageUtils.js
  client/src/utils/selector.js
  client/src/views/components/BaeminInput/BaeminInput.css
  client/src/views/components/BaeminInputField/BaeminInputField.css
  client/src/views/components/BaeminInputField/BaeminInputField.js
  client/src/views/page-components/MainPage/LoginFieldset/LoginFieldset.js
  client/src/views/page-components/MainPage/LoginScreen/LoginScreen.js
  client/src/views/page-components/MainPage/LogoutScreen/LogoutScreen.js
  client/src/views/page-components/MainPage/MainPage.js
  client/src/views/page-components/MainPage/SignupFieldset/SignupFieldset.js
  client/src/views/page-components/MainPage/SignupScreen/SignupScreen.js
  client/src/views/page-components/MainPage/UserSlide/UserSlide.js
  server/constants/errorMessages.js
  server/constants/regex.js
  server/controller/auth.js
  server/query/authQuery.js
Labels: BE, FE, 작업 완료

#43 [Feature/#18] 채팅 목록 받아오기
  client/src/apis/chatAPI.js
  client/src/utils/formatDate.js
  client/src/views/components/ChatRoomList/ChatRoomList.css
  client/src/views/components/ChatRoomList/ChatRoomList.js
  client/src/views/components/components.css
  client/src/views/page-components/ChatDetailPage/ChatDetaiPageHeader/ChatDetailPageHeader.js
  client/src/views/page-components/ChatDetailPage/ChatDetailPage.js
  client/src/views/page-components/ChatListPage/ChatListPage.css
  client/src/views/page-components/ChatListPage/ChatListPage.js
  client/src/views/page-components/MainPage/ChatListScreen/ChatListScreen.js
  client/src/views/page-components/MainPage/MainPage.js
  client/src/views/page-components/MainPage/MenuSlide/MenuSlide.js
  server/connection/socket.js
  server/controller/chat.js
  server/data/auth.js
  server/data/chat.js
  server/data/product.js
  server/middleware/checkToken.js
  server/package.json
  server/query/createTableQuery.js
  server/router/chatRouter.js
Labels: BE, FE, 작업 완료
